GET http://localhost:4000/user-api/users

###
GET http://localhost:4000/product-api/products
###
GET http://localhost:4000/user-api/users/1

###
POST http://localhost:4000/user-api/new-user
Content-Type: application/json

{
    "id":4,
    "name":"vikas"
}


###
PUT http://localhost:4000/user-api/user
Content-Type: application/json

{
    "id":12,
    "name":"ravi kumar"
}

###
DELETE http://localhost:4000/user-api/user/12