GET http://localhost:4000/user-api/users

###
GET http://localhost:4000/product-api/products
###

GET http://localhost:4000/user-api/users/kiran

###
POST http://localhost:4000/user-api/new-user
Content-Type: application/json

{
   
    "username":"kiran",
    "password":"kiran",
    "email":"kiran@mail.com"
}

###
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
   
    "username":"bhanu",
    "password":"bhanu"
   
}


###
PUT http://localhost:4000/user-api/user
Content-Type: application/json

{
    "name":"kiran",
    "age":42,
    "city":"bangalore"
}

###
DELETE http://localhost:4000/user-api/user/kiran